spring.application.name=camunda

# Server
server.port=8082

# Camunda 8 connection
zeebe.client.broker.gateway-address=localhost:26500
zeebe.client.security.plaintext=true

# H2 Database
spring.datasource.url=jdbc:h2:mem:demodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
