spring.application.name=shipping-service
server.port=8084

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Camunda / Zeebe
zeebe.client.broker.gateway-address=localhost:26500
zeebe.client.security.plaintext=true
